### ISSUE TITLE
PMD in GitHub Actions.

### ISSUE THREAD

**Issue by amuradyan** [amuradyan/SuperHotWinXRoyal777#21]
We should also add this to our GitHub Actions.

_Originally posted by @amuradyan in https://github.com/amuradyan/SuperHotWinXRoyal777/issues/19#issuecomment-1032563572_

**Comment by RishiKumarRay** [comment]
do you have the ruleset.xml?

**Comment by RishiKumarRay** [comment]
@amuradyan please check this https://github.com/RishiKumarRay/SuperHotWinXRoyal777/actions/runs/1834361454
also the report is generated via artificat
![Screenshot from 2022-02-12 22-46-53](https://user-images.githubusercontent.com/87641376/153721218-82d82766-75df-48ca-a3b6-a28ea9c4eb61.png)

**Comment by amuradyan** [comment]
@RishiKumarRay Looks great. Wanna open a PR? We do not have any contribution guides yet, so feel free. 

Thanks again.

**Comment by RishiKumarRay** [comment]
@amuradyan yeah sure i will open it right now

**Comment by RishiKumarRay** [comment]
@amuradyan please review also i had added master branch in github actions so as to do the testing of this pmd actions as the rule file was present in master branch itself
